In [1]:
import numpy as np
import tensorflow as tf
sess = tf.InteractiveSession()

1-d array (a.k.a. vector)

In [2]:
_x = np.arange(10)
_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
_x[0]

0

In [4]:
_x[2]

2

In [5]:
_x[0:5]

array([0, 1, 2, 3, 4])

In [6]:
_x[:5]

array([0, 1, 2, 3, 4])

In [7]:
_x[5:]

array([5, 6, 7, 8, 9])

In [9]:
_head, _tail = _x[:5], _x[5:] # Slicing
print(_head, _tail)

[0 1 2 3 4] [5 6 7 8 9]


In [10]:
_x[1:9:2]

array([1, 3, 5, 7])

In [11]:
_x[::2]

array([0, 2, 4, 6, 8])

In [12]:
_x[::-1] # Reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

1-d tensor

In [13]:
x = tf.convert_to_tensor(_x)

In [14]:
x.eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[:3].eval()

array([0, 1, 2])

In [16]:
x[3].eval()

3

In [17]:
x[5:].eval()

array([5, 6, 7, 8, 9])

In [18]:
x[1:5:2].eval()

array([1, 3])

In [19]:
x[::-1].eval()

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
head, tail = x[:4], x[4:] # Slicing

In [21]:
head.eval()

array([0, 1, 2, 3])

In [22]:
tail.eval()

array([4, 5, 6, 7, 8, 9])

2-d arrays (a.k.a. matrices)

In [23]:
_X = np.arange(1, 11).reshape([2, 5])
_X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
_X[0, 1]

2

In [25]:
_X[:, 1]

array([2, 7])

In [26]:
_X[:, 1:2]

array([[2],
       [7]])

In [28]:
_X[[0, 1], [3, 4]] # Multiple indexing

array([ 4, 10])

2-d tensors

In [29]:
X = tf.convert_to_tensor(_X)
X.eval()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
X[0,3].eval()

4

In [31]:
X[:, 1].eval()

array([2, 7])

In [33]:
X[0:1, 1:5].eval()

array([[2, 3, 4, 5]])

In [35]:
X[[0, 1], [1, 3]] # Multiple indexing: not woking

TypeError: can only concatenate list (not "int") to list