In [1]:
import numpy as np
import tensorflow as tf
sess = tf.InteractiveSession()

## Arithmetic operations

In [2]:
_x = np.array([1, 2, 3], np.float32)
_y = np.array([4, 5, 6], np.float32)

In [3]:
_x + _y

array([ 5.,  7.,  9.], dtype=float32)

In [4]:
_x - _y

array([-3., -3., -3.], dtype=float32)

In [5]:
_x * _y

array([  4.,  10.,  18.], dtype=float32)

In [6]:
_x / _y

array([ 0.25      ,  0.40000001,  0.5       ], dtype=float32)

In [7]:
np.add(_x, _y)

array([ 5.,  7.,  9.], dtype=float32)

In [8]:
np.subtract(_x, _y)

array([-3., -3., -3.], dtype=float32)

In [9]:
np.multiply(_x, _y)

array([  4.,  10.,  18.], dtype=float32)

In [10]:
np.divide(_x, _y)

array([ 0.25      ,  0.40000001,  0.5       ], dtype=float32)

In [11]:
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)

In [12]:
print(x + y, x - y, x*y, x/y)

Tensor("add:0", shape=(3,), dtype=float32) Tensor("sub:0", shape=(3,), dtype=float32) Tensor("mul:0", shape=(3,), dtype=float32) Tensor("truediv:0", shape=(3,), dtype=float32)


## Sums, products, mean, max, min ...
- np.sum(arry, axis) == tf.reduce_sum(tensor, axis)
- np.prod(arry, axis) == tf.reduce_prod(tensor, axis)
- np.mean(arry, axis) == tf.reduce_mean(tensor, axis)
- np.max(arry, axis) == tf.reduce_max(tensor, axis)
- np.min(arry, axis) == tf.reduce_min(tensor, axis)
- np.argmax(arry, axis) == tf.argmax(tensor, axis)
- np.argmin(arry, axis) == tf.argmin(tensor, axis)




In [13]:
_x = np.arange(1, 11).reshape((2, 5))

In [14]:
_x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.sum(_x, axis=1)

array([15, 40])

In [16]:
np.prod(_x, axis=0)

array([ 6, 14, 24, 36, 50])

In [17]:
np.max(_x, axis=0)

array([ 6,  7,  8,  9, 10])

In [18]:
np.min(_x)

1

In [19]:
np.argmax(_x)

9

In [20]:
np.argmax(_x, axis=1)

array([4, 4], dtype=int64)

In [21]:
np.mean(_x, axis=1)

array([ 3.,  8.])

In [22]:
x = tf.constant(_x)

In [23]:
x.eval()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
tf.reduce_sum(x).eval()

55

In [25]:
tf.reduce_sum(x, 1).eval()

array([15, 40])

In [26]:
tf.reduce_prod(x, 1).eval()

array([  120, 30240])

In [27]:
tf.reduce_max(x, 0).eval()

array([ 6,  7,  8,  9, 10])

In [28]:
tf.reduce_min(x, 1).eval()

array([1, 6])

In [29]:
tf.argmin(x, 1).eval()

array([0, 0], dtype=int64)

In [30]:
tf.reduce_mean(x, 0).eval()

array([3, 4, 5, 6, 7])

## Linear algebra

- np.dot(1d, 1d) == tf.reduce_sum(1d * 1d) 
- np.dot(2d, 2d) == tf.matmul(2d, 2d)

In [31]:
_v1 = np.array([1, 2], np.float32)
_v2 = np.array([3, 4], np.float32)
_vv1 = np.array([[1, 2], [1, 2]], np.float32)
_vv2 = np.array([[3, 4], [3, 4]], np.float32)

In [32]:
np.dot(_v1, _v2)

11.0

In [33]:
np.dot(_v2, _v1)

11.0

In [34]:
np.dot(_vv1, _vv2)

array([[  9.,  12.],
       [  9.,  12.]], dtype=float32)

In [35]:
v1 = tf.convert_to_tensor(_v1)
v2 = tf.convert_to_tensor(_v2)
vv1 = tf.convert_to_tensor(_vv1)
vv2 = tf.convert_to_tensor(_vv2)

In [36]:
tf.reduce_sum(v1 * v2).eval()

11.0

In [37]:
tf.matmul(vv1, vv2).eval()

array([[  9.,  12.],
       [  9.,  12.]], dtype=float32)

## Reshaping

- reshape(obj, newshape) OR np.ndarray.reshape(newshape)
- expand_dims(obj, axis)
- transpose(obj, axes)
- squeeze(obj, axes)

In [38]:
_x = np.arange(1, 9, dtype=np.int32)

In [39]:
_x.shape

(8,)

In [40]:
_x2 = np.expand_dims(_x, -1)

In [41]:
_x2.shape

(8, 1)

In [42]:
_x2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [43]:
_x3 = np.reshape(_x, [4,2])

In [44]:
_x3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
_x3.shape

(4, 2)

In [46]:
_x4 = np.transpose(_x3, [1, 0])

In [47]:
_x2.shape

(8, 1)

In [48]:
_x5 = np.squeeze(_x2)
_x5.shape

(8,)

In [49]:
x = tf.convert_to_tensor(_x)
x.eval()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
X = tf.expand_dims(x, -1)
X

<tf.Tensor 'ExpandDims:0' shape=(8, 1) dtype=int32>

In [51]:
x2 = tf.reshape(x, [4, 2])
x2

<tf.Tensor 'Reshape:0' shape=(4, 2) dtype=int32>

In [52]:
x3 = tf.transpose(X, [1, 0])
x3.eval()

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [53]:
x4 = tf.squeeze(x3)
x4

<tf.Tensor 'Squeeze:0' shape=(8,) dtype=int32>