In [1]:
import numpy as np
import tensorflow as tf

Notation: _x, _y, _z: array, x, y, z: tensor

In [2]:
# For convenience
sess = tf.InteractiveSession()

Arrays can be created from Python lists or tuples.

In [3]:
_x1 = np.array([1,2,3,4,5])# from list
_x2 = np.array((1,2,3,4,5)) # from tuple
print(_x1, _x2)

[1 2 3 4 5] [1 2 3 4 5]


It's always a good idea to explicitly assign the data type when creating an array.

In [4]:
_x1 = np.array([1,2,3,4,5], dtype=np.int32)

In [5]:
_x1.dtype

dtype('int32')

If you want to change the data type of an array,

In [6]:
_x1 = _x1.astype(np.float32)

In [7]:
_x1.dtype

dtype('float32')

In [8]:
_x1.shape # shape

(5,)

In [9]:
_x1.ndim # ndim or rank in TensorFlow terminology

1

In [10]:
_X1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
_X1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

In [11]:
print(_X1.shape)
print(_X1.dtype)

(2, 3)
float32


Tensors can be made from Python scalars, lists, or numpy arrays.

In [12]:
tf.constant(1) # from Python scalar

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [13]:
tf.constant([1, 2, 3]) # from list

<tf.Tensor 'Const_1:0' shape=(3,) dtype=int32>

In [14]:
tf.constant(np.array([1, 2, 3], np.int64)) # Best practice!

<tf.Tensor 'Const_2:0' shape=(3,) dtype=int64>

Or you can convert them to a tensor like this.

In [15]:
X1 = tf.convert_to_tensor(_X1)
X1

<tf.Tensor 'Const_3:0' shape=(2, 3) dtype=float32>

In [16]:
X1.eval()

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

In [17]:
X1.dtype

tf.float32

In [18]:
X1.get_shape().as_list()

[2, 3]

Create an array filled with zeros or ones.

In [19]:
_zeros = np.zeros([3, 5], np.int32)
_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
_ones = np.ones([3, 5], np.float32)
_ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [21]:
_fives = np.ones([3, 5], np.float32) * 5
_fives

array([[ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.]], dtype=float32)

Create an array with the same shape and dtype as a certain array, but filled with zeros or ones.

In [22]:
X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)

In [23]:
X2 = tf.zeros_like(X)
X2.eval()

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
X3 = tf.ones_like(X)
X3.eval()

array([[1, 1, 1],
       [1, 1, 1]])

Create a tensor filled with zeros or ones.

In [25]:
X4 = tf.zeros_like(X1)
X4.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [26]:
X5 = tf.ones_like(X1)
X5.eval()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

Create some regularly spaced array.

In [27]:
_x1 = np.linspace(0, 10, 5) # five elements from 0 to 10 (inclusive)
_x1

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [28]:
_x2 = np.arange(0, 10, 2, dtype=np.float32) # from 0 to 10 (exclusive), step=2
_x2

array([ 0.,  2.,  4.,  6.,  8.], dtype=float32)

Create some regularly spaced tensor.

In [29]:
x1 = tf.linspace(0., 10, 5)
x1.eval()

array([  0. ,   2.5,   5. ,   7.5,  10. ], dtype=float32)

In [30]:
x2 = tf.range(0, 10, 2)
x2.eval()

array([0, 2, 4, 6, 8])

Create random arrays

In [31]:
_x = np.random.normal(3, 0.3, [30000, 4])
_x

array([[ 2.79778296,  3.31195815,  2.9572616 ,  3.41099159],
       [ 3.06707386,  2.75770653,  3.56699116,  3.06269411],
       [ 2.87343592,  2.42140926,  2.90308584,  2.94035599],
       ..., 
       [ 3.09170575,  2.83684115,  3.03489958,  2.87395914],
       [ 3.64564372,  2.97728388,  2.99041326,  3.1037937 ],
       [ 3.24632579,  3.38332561,  2.83951565,  2.95078544]])

In [32]:
_x2 = np.random.uniform(3, 10, [3, 4])
_x2

array([[ 9.03397168,  6.85251358,  3.19748006,  9.27063369],
       [ 6.27354201,  7.78365266,  6.22690345,  4.15928007],
       [ 7.96648371,  6.904826  ,  8.51664221,  7.45611329]])

In [33]:
x1 = tf.random_normal([3, 4], 0, 1, dtype=tf.float64)
x1.eval()

array([[-2.1235378 ,  0.42768423, -1.1226624 ,  1.0635717 ],
       [-0.12094115, -2.04292045,  0.65923468,  0.66866386],
       [ 0.20845262,  1.15842827,  0.55973512, -0.33221781]])

In [34]:
x2 = tf.random_uniform([3, 4], 3, 10, dtype=tf.int32)
x2.eval()

array([[3, 7, 7, 6],
       [6, 7, 5, 9],
       [4, 8, 7, 7]])

Save and load an array.

In [35]:
np.save('_x.npy', _x)

In [36]:
np.load('_x.npy')

array([[ 2.79778296,  3.31195815,  2.9572616 ,  3.41099159],
       [ 3.06707386,  2.75770653,  3.56699116,  3.06269411],
       [ 2.87343592,  2.42140926,  2.90308584,  2.94035599],
       ..., 
       [ 3.09170575,  2.83684115,  3.03489958,  2.87395914],
       [ 3.64564372,  2.97728388,  2.99041326,  3.1037937 ],
       [ 3.24632579,  3.38332561,  2.83951565,  2.95078544]])

In [37]:
np.savez('_x_x2.npz', _x=_x, _x2=_x2) # multiple arrays

In [38]:
_x, _x2 = np.load('_x_x2.npz')['_x'], np.load('_x_x2.npz')['_x2']

In [39]:
_x

array([[ 2.79778296,  3.31195815,  2.9572616 ,  3.41099159],
       [ 3.06707386,  2.75770653,  3.56699116,  3.06269411],
       [ 2.87343592,  2.42140926,  2.90308584,  2.94035599],
       ..., 
       [ 3.09170575,  2.83684115,  3.03489958,  2.87395914],
       [ 3.64564372,  2.97728388,  2.99041326,  3.1037937 ],
       [ 3.24632579,  3.38332561,  2.83951565,  2.95078544]])

In [40]:
_x2

array([[ 9.03397168,  6.85251358,  3.19748006,  9.27063369],
       [ 6.27354201,  7.78365266,  6.22690345,  4.15928007],
       [ 7.96648371,  6.904826  ,  8.51664221,  7.45611329]])